
export const minterAbi = [
  {
    "inputs":[
      {
          "internalType":"address",
          "name":"_nftContract",
          "type":"address"
      },
      {
          "internalType":"address",
          "name":"_sastToken",
          "type":"address"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
     "inputs":[],
     "name":"AlreadyMinted",
     "type":"error"
  },
  {
     "inputs":[],
     "name":"InsufficientSASTBalance",
     "type":"error"
  },
  {
     "inputs":[],
     "name":"InvalidMintQuantity",
     "type":"error"
  },
  {
     "inputs":[],
     "name":"InvalidTokenAddress",
     "type":"error"
  },
  {
     "inputs":[],
     "name":"Unauthorized",
     "type":"error"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"oldQuantity",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"newQuantity",
           "type":"uint256"
        }
     ],
     "name":"MintQuantityUpdated",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"oldTokenId",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"newTokenId",
           "type":"uint256"
        }
     ],
     "name":"MintableTokenIdUpdated",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"user",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"uint256",
           "name":"tokenId",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"quantity",
           "type":"uint256"
        }
     ],
     "name":"NFTMinted",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"oldBalance",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"newBalance",
           "type":"uint256"
        }
     ],
     "name":"RequiredBalanceUpdated",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"oldAddress",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"newAddress",
           "type":"address"
        }
     ],
     "name":"SASTTokenUpdated",
     "type":"event"
  },
  {
     "inputs":[
        {
           "internalType":"address[]",
           "name":"users",
           "type":"address[]"
        }
     ],
     "name":"batchMintNFTs",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"user",
           "type":"address"
        }
     ],
     "name":"canMint",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"getTotalTokensMinted",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"user",
           "type":"address"
        }
     ],
     "name":"getUserSASTBalance",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "name":"hasMinted",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"mintNFT",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"mintQuantity",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"mintableTokenId",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"nftContract",
     "outputs":[
        {
           "internalType":"contract IAirswapNFT",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"owner",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"requiredSASTBalance",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"sastToken",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[],
     "name":"totalMinted",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_newOwner",
           "type":"address"
        }
     ],
     "name":"transferOwnership",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"_mintQuantity",
           "type":"uint256"
        }
     ],
     "name":"updateMintQuantity",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"_mintableTokenId",
           "type":"uint256"
        }
     ],
     "name":"updateMintableTokenId",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"_requiredBalance",
           "type":"uint256"
        }
     ],
     "name":"updateRequiredBalance",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_sastToken",
           "type":"address"
        }
     ],
     "name":"updateSASTToken",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  }
] as const;
